services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-web-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: ["dotnet build src/Web/Web.csproj -c Debug && exec dotnet /app/src/Web/bin/Debug/net8.0/Web.dll --urls http://0.0.0.0:5042"]

  api:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-api-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: ["dotnet build src/Api/Api.csproj -c Debug && exec dotnet /app/src/Api/bin/Debug/net8.0/Api.dll --urls http://0.0.0.0:7000"]
